theme: jekyll-theme-minimal
title: Yimu Pan's homepage
description: Welcome!

# Sidebar Configuration
sidebar:
  name: Yimu Pan
  picture: /assets/images/headshot_lines.jpeg
  contact:
    email_primary: ymp5078@psu.edu
    email_secondary: yimu1123955008@gmail.com
    github: https://github.com/ymp5078
    linkedin: https://www.linkedin.com/in/yimu-pan-669790180/
    google_scholar: https://scholar.google.com/citations?user=zIM2dLcAAAAJ
